package raidzero.robot;

import edu.wpi.first.wpilibj.RobotBase;

/**
 * Do NOT edit this file.
 */
public final class Main {

    private Main() {}

    public static void main(String... args) {
        RobotBase.startRobot(Robot::new);
    }

}
